# Generated by Django 5.1.7 on 2025-03-17 16:00

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(blank=True, default=0)),
                ('product_description', models.TextField(blank=True, default='')),
                ('specifications', models.TextField(blank=True, default='')),
                ('price', models.IntegerField(blank=True, default=0)),
                ('strikeout_price', models.IntegerField(blank=True, default=0)),
                ('image_1', models.ImageField(blank=True, upload_to='products/')),
                ('image_2', models.ImageField(blank=True, upload_to='products/')),
                ('image_3', models.ImageField(blank=True, upload_to='products/')),
                ('image_4', models.ImageField(blank=True, upload_to='products/')),
                ('image_5', models.ImageField(blank=True, upload_to='products/')),
                ('image_6', models.ImageField(blank=True, upload_to='products/')),
                ('image_7', models.ImageField(blank=True, upload_to='products/')),
                ('key_words', models.CharField(blank=True, default='', max_length=255)),
                ('juice_type', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=255)),
                ('slug', models.SlugField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('online', 'online'), ('cod', 'cod')], default='', max_length=10)),
                ('total_price', models.IntegerField(blank=True, default=0)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('name', models.CharField(blank=True, default='', max_length=55)),
                ('phone', models.CharField(blank=True, default='', max_length=25)),
                ('email', models.CharField(blank=True, default='', max_length=35)),
                ('house_no', models.CharField(blank=True, default='', max_length=35)),
                ('area', models.CharField(blank=True, default='', max_length=35)),
                ('city', models.CharField(blank=True, default='', max_length=35)),
                ('state', models.CharField(blank=True, default='', max_length=35)),
                ('pin_code', models.CharField(blank=True, default='', max_length=15)),
                ('landmark', models.CharField(blank=True, default='', max_length=35)),
                ('Order_status', models.CharField(choices=[('Pending', 'Pending'), ('Order placed', 'Order placed'), ('Order conformed', 'Order conformed'), ('Processing', 'Processing'), ('Ready to ship', 'Ready to ship'), ('Dispatched', 'Dispatched'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('payment_status', models.CharField(blank=True, default='', max_length=35)),
                ('j_cart_product', models.IntegerField(blank=True, default=0)),
                ('uuid', models.CharField(blank=True, default='', max_length=135)),
                ('transaction_id', models.CharField(blank=True, default='', max_length=135)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_qty', models.IntegerField(blank=True, default=0)),
                ('amount', models.IntegerField(blank=True, default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
        ),
    ]
