# Generated by Django 5.1.7 on 2025-03-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='j_cart_product',
            field=models.TextField(blank=True, default=''),
        ),
    ]
